import type { Metadata } from "next";
import {Poppins} from 'next/font/google'
// import localfont from 'next/font'
import "./globals.css";
import { Toaster } from "sonner";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
// const inter = localfont({})
const inter = Poppins({weight :'400' , subsets : ['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <Toaster position="bottom-right"></Toaster>
        {children}
      </body>
    </html>
  );
}
